window.GDER_ENTITIES = [
  {
    "id": "dao-uniswap-foundation",
    "name": "Uniswap Foundation",
    "legalName": "Uniswap Foundation",
    "entityType": "foundation",
    "jurisdiction": "United States",
    "formationCountry": "United States",
    "legalWrapperType": "501(c)(4) nonprofit",
    "status": "qualified",
    "basis": "Independent 501(c)(4) nonprofit stewarding UNI-token governance and protocol ecosystem work.",
    "canonicalUrl": "https://www.uniswapfoundation.org/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-arbitrum-foundation",
    "name": "Arbitrum Foundation",
    "legalName": "The Arbitrum Foundation",
    "entityType": "foundation",
    "jurisdiction": "Cayman Islands",
    "formationCountry": "Cayman Islands",
    "legalWrapperType": "foundation company",
    "status": "qualified",
    "basis": "Official Cayman foundation company created as the DAO's legal and operational wrapper and governance support body.",
    "canonicalUrl": "https://arbitrum.foundation/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-optimism-foundation",
    "name": "Optimism Foundation",
    "legalName": "The Optimism Foundation",
    "entityType": "foundation",
    "jurisdiction": "Cayman Islands",
    "formationCountry": "Cayman Islands",
    "legalWrapperType": "foundation company",
    "status": "qualified",
    "basis": "Official Cayman foundation company supporting OP-governed collective operations.",
    "canonicalUrl": "https://www.optimism.io/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_forum"
  },
  {
    "id": "dao-ens-foundation-limited",
    "name": "ENS Foundation",
    "legalName": "ENS Foundation Limited",
    "entityType": "foundation",
    "jurisdiction": "Cayman Islands",
    "formationCountry": "Cayman Islands",
    "legalWrapperType": "foundation company limited by guarantee",
    "status": "qualified",
    "basis": "Official Cayman foundation company representing ENS DAO in real-world matters while ENS token holders govern the protocol and treasury.",
    "canonicalUrl": "https://ens.domains/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-ape-foundation",
    "name": "Ape Foundation",
    "legalName": "Ape Foundation",
    "entityType": "foundation",
    "jurisdiction": "Cayman Islands",
    "formationCountry": "Cayman Islands",
    "legalWrapperType": "foundation",
    "status": "qualified",
    "basis": "Foundation acts as the legal backing and day-to-day administrator for ApeCoin DAO governance.",
    "canonicalUrl": "https://apecoin.com/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_forum"
  },
  {
    "id": "dao-pyth-dao-llc",
    "name": "Pyth DAO",
    "legalName": "Pyth DAO LLC",
    "entityType": "llc",
    "jurisdiction": "Republic of Marshall Islands",
    "formationCountry": "Marshall Islands",
    "legalWrapperType": "DAO LLC",
    "status": "qualified",
    "basis": "Official DAO LLC operating agreement and constitution tie token-staker governance to a Marshall Islands DAO LLC.",
    "canonicalUrl": "https://www.pyth.network/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_forum"
  },
  {
    "id": "dao-helium-foundation",
    "name": "Helium Foundation",
    "legalName": "Decentralized Wireless Foundation Inc.",
    "entityType": "nonprofit",
    "jurisdiction": "United States",
    "formationCountry": "United States",
    "legalWrapperType": "501(c)(6) nonprofit",
    "status": "qualified",
    "basis": "Recognizable nonprofit steward supporting HIP governance and network education and grants for the Helium ecosystem.",
    "canonicalUrl": "https://www.helium.foundation/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-jito-foundation",
    "name": "Jito Foundation",
    "legalName": "Jito Foundation",
    "entityType": "foundation",
    "jurisdiction": "Cayman Islands",
    "formationCountry": "Cayman Islands",
    "legalWrapperType": "foundation company",
    "status": "qualified",
    "basis": "Official Cayman foundation company formed to serve the DAO, with constitution, bylaws, and JTO governance processes.",
    "canonicalUrl": "https://www.jito.network/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_forum"
  },
  {
    "id": "dao-tezos-foundation",
    "name": "Tezos Foundation",
    "legalName": "Tezos Foundation",
    "entityType": "foundation",
    "jurisdiction": "Switzerland",
    "formationCountry": "Switzerland",
    "legalWrapperType": "Swiss foundation",
    "status": "qualified",
    "basis": "Swiss foundation supporting an on-chain self-amending governance system.",
    "canonicalUrl": "https://tezos.foundation/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-interchain-foundation",
    "name": "Interchain Foundation",
    "legalName": "Interchain Foundation",
    "entityType": "foundation",
    "jurisdiction": "Switzerland",
    "formationCountry": "Switzerland",
    "legalWrapperType": "Swiss nonprofit foundation",
    "status": "qualified",
    "basis": "Swiss nonprofit supporting Cosmos public goods and governance while Cosmos Hub uses on-chain proposal and parameter governance.",
    "canonicalUrl": "https://interchain.io/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-cardano-foundation",
    "name": "Cardano Foundation",
    "legalName": "Cardano Foundation",
    "entityType": "foundation",
    "jurisdiction": "Switzerland",
    "formationCountry": "Switzerland",
    "legalWrapperType": "Swiss not-for-profit foundation",
    "status": "qualified",
    "basis": "Swiss not-for-profit foundation attached to Cardano's token-holder governance and ecosystem stewardship.",
    "canonicalUrl": "https://cardanofoundation.org/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-zksync-association",
    "name": "ZKsync Association",
    "legalName": "ZKsync Association",
    "entityType": "association",
    "jurisdiction": "Austria",
    "formationCountry": "Austria",
    "legalWrapperType": "nonprofit association",
    "status": "qualified",
    "basis": "Officially documented nonprofit association that anchors ZKsync governance and delegate participation.",
    "canonicalUrl": "https://www.zknation.io/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-mina-foundation",
    "name": "Mina Foundation",
    "legalName": "Mina Foundation",
    "entityType": "foundation",
    "jurisdiction": "Switzerland",
    "formationCountry": "Switzerland",
    "legalWrapperType": "Stiftung / public benefit foundation",
    "status": "qualified",
    "basis": "Swiss foundation tied to MINA token governance and decentralization commitments.",
    "canonicalUrl": "https://www.minafoundation.com/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-1inch-foundation",
    "name": "1inch Foundation",
    "legalName": "1inch Foundation",
    "entityType": "nonprofit",
    "jurisdiction": null,
    "formationCountry": null,
    "legalWrapperType": "independent non-profit",
    "status": "qualified",
    "basis": "Independent nonprofit issuer and steward linked to 1inch DAO token governance and off-chain stewardship.",
    "canonicalUrl": "https://1inch.io/foundation/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-safe-ecosystem-foundation",
    "name": "Safe Ecosystem Foundation",
    "legalName": "Safe Ökosystem Stiftung",
    "entityType": "foundation",
    "jurisdiction": "Switzerland",
    "formationCountry": "Switzerland",
    "legalWrapperType": "Stiftung",
    "status": "qualified",
    "basis": "Swiss foundation and nonprofit behind Safe governance, grants, and ecosystem stewardship.",
    "canonicalUrl": "https://safefoundation.org/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-wormhole-foundation",
    "name": "Wormhole Foundation",
    "legalName": "Wormhole Foundation",
    "entityType": "foundation",
    "jurisdiction": "Cayman Islands",
    "formationCountry": "Cayman Islands",
    "legalWrapperType": "foundation",
    "status": "qualified",
    "basis": "Official foundation with Cayman address and W-token governance framework stewarding protocol governance.",
    "canonicalUrl": "https://wormhole.foundation/",
    "confidenceTier": "high",
    "governanceAnchorType": "blog_post"
  },
  {
    "id": "dao-celo-foundation",
    "name": "Celo Foundation",
    "legalName": "Celo Foundation",
    "entityType": "foundation",
    "jurisdiction": "Delaware, United States",
    "formationCountry": "United States",
    "legalWrapperType": "mission-driven foundation",
    "status": "qualified",
    "basis": "Identifiable foundation behind Celo with a public governance repository and active community proposal process.",
    "canonicalUrl": "https://celo.org/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-starknet-foundation",
    "name": "Starknet Foundation",
    "legalName": "Starknet Foundation",
    "entityType": "foundation",
    "jurisdiction": "Cayman Islands",
    "formationCountry": "Cayman Islands",
    "legalWrapperType": "not-for-profit",
    "status": "qualified",
    "basis": "Not-for-profit foundation created to support Starknet and roll out token-holder governance.",
    "canonicalUrl": "https://www.starknet.io/",
    "confidenceTier": "high",
    "governanceAnchorType": "blog_post"
  },
  {
    "id": "dao-balancer-foundation",
    "name": "Balancer Foundation",
    "legalName": "Balancer Foundation",
    "entityType": "foundation",
    "jurisdiction": "Cayman Islands",
    "formationCountry": "Cayman Islands",
    "legalWrapperType": "foundation",
    "status": "qualified",
    "basis": "Officially incorporated legal proxy for BalancerDAO, used for contracts and DAO operations.",
    "canonicalUrl": "https://balancer.fi/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_forum"
  },
  {
    "id": "dao-aleph-zero-foundation",
    "name": "Aleph Zero Foundation",
    "legalName": "Aleph Zero Stiftung",
    "entityType": "foundation",
    "jurisdiction": "Switzerland",
    "formationCountry": "Switzerland",
    "legalWrapperType": "Stiftung",
    "status": "qualified",
    "basis": "Swiss foundation with board-governed treasury and publicly documented token-governance evolution.",
    "canonicalUrl": "https://alephzero.org/",
    "confidenceTier": "high",
    "governanceAnchorType": "blog_post"
  },
  {
    "id": "dao-manta-foundation",
    "name": "Manta Foundation",
    "legalName": "Manta Foundation",
    "entityType": "foundation",
    "jurisdiction": null,
    "formationCountry": null,
    "legalWrapperType": "foundation",
    "status": "qualified",
    "basis": "Foundation treasury and governance arrangements are publicly documented in official Manta governance proposals.",
    "canonicalUrl": "https://foundation.manta.network/",
    "confidenceTier": "high",
    "governanceAnchorType": "proposal"
  },
  {
    "id": "dao-nouns-foundation",
    "name": "Nouns Foundation",
    "legalName": "Nouns Foundation",
    "entityType": "foundation",
    "jurisdiction": "Cayman Islands",
    "formationCountry": "Cayman Islands",
    "legalWrapperType": "foundation company",
    "status": "qualified",
    "basis": "Foundation provides the legal wrapper and veto layer around Nouns DAO governance and risk management.",
    "canonicalUrl": "https://nouns.wtf/",
    "confidenceTier": "high",
    "governanceAnchorType": "onchain_vote"
  },
  {
    "id": "dao-the-lao",
    "name": "The LAO",
    "legalName": "The LAO",
    "entityType": "llc",
    "jurisdiction": "Delaware, United States",
    "formationCountry": "United States",
    "legalWrapperType": "Delaware LLC",
    "status": "qualified",
    "basis": "Official Delaware LLC wrapper administered via smart contracts and member voting.",
    "canonicalUrl": "https://thelao.io/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  },
  {
    "id": "dao-metacartel-ventures",
    "name": "MetaCartel Ventures",
    "legalName": "MetaCartel Ventures",
    "entityType": "llc",
    "jurisdiction": "Delaware, United States",
    "formationCountry": "United States",
    "legalWrapperType": "member-managed Delaware LLC",
    "status": "qualified",
    "basis": "Official materials describe a member-managed Delaware LLC tightly coupled to Moloch v2 contracts for venture DAO governance.",
    "canonicalUrl": "https://metacartel.xyz/",
    "confidenceTier": "high",
    "governanceAnchorType": "official_site"
  },
  {
    "id": "dao-flamingo-dao-llc",
    "name": "Flamingo DAO",
    "legalName": "Flamingo DAO LLC",
    "entityType": "llc",
    "jurisdiction": "United States",
    "formationCountry": "United States",
    "legalWrapperType": "LLC",
    "status": "qualified",
    "basis": "Member-managed NFT investment DAO with operating agreement amendments and investment decisions governed by member votes.",
    "canonicalUrl": "https://flamingodao.xyz/",
    "confidenceTier": "high",
    "governanceAnchorType": "governance_docs"
  }
];
